language: php

php:
  - '7.0'
  - '7.1'
  - nightly

before_script:
  - composer self-update

install:
  - composer install --prefer-source

script:
  - mkdir -p build/logs
  - phpunit --coverage-clover build/logs/clover.xml
  - composer lint

after_success:
  - vendor/bin/coveralls -v
